# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  decode-cert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Retrieve the secret and decode it to a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.BASE64_CERT }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > cert.crt
      
      - name: Show decoded certificate information
        run: |
          openssl x509 -in cert.crt -text -noout
